table Orders
	lineageTag: 9987a5d5-39d8-472c-b4d9-49ca5cac55a5

	measure 'Total Sales' = SUM(Orders[Sales])
		lineageTag: 9979edd2-a30e-4919-92f7-2b70caf86e67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(Orders[Profit])
		lineageTag: af3e4283-7165-4d53-a0d8-26de2d84de66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 3f0ea829-ae36-45c0-b9df-a4e9d0d4f4b8
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 1f460061-ab5a-4b23-bd94-fc20c4256481
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1b8ea540-ed3b-4326-9c85-2d5195ac7adf
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: b9ff5e93-a4c9-48d3-9bd1-e4e0b654f23d
			defaultHierarchy: LocalDateTable_ba1e04bf-0069-4f52-8706-f5df7f5777fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 503f5577-bc41-410a-b694-079a74a60cbe
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: ea19986d-61e9-4fe0-9edb-9ae5807484f2
			defaultHierarchy: LocalDateTable_3b0fcc3c-7e37-4a76-9b79-ba2ca5c6d7e7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: c1c87e30-c144-490e-b3f3-dba8636b8833
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 1fb586e8-c89e-414b-bc33-d695d0fa4e2d
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: f9f509fe-ad8f-491e-b090-f1ad4b301a1f
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 86fca945-9c5e-49cb-8844-1dbe94e3a575
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 888e9f70-fc34-45b3-95e3-5317950424e9
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 32208081-0523-4bbd-9770-5889a9003568
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 34a0fa74-b30c-4f3e-b063-0952144dad92
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 33a70295-2ff5-491a-a2be-6b25d9a3c211
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d9a03da5-4f0f-486b-ac9f-6cff53d4f46f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 92927f6a-98c2-4e4d-bc68-d8a573621ad6
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4cb6dac5-9bc7-4b6a-9172-a80b0d0f51a9
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 371a175a-c9eb-48d6-8c00-8516027e1f1d
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 3e42f373-165b-4b41-b6c3-3432514f64ba
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 84c4aa09-8eef-44b6-afd8-3a1641c9ef9f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 1863f860-c4b8-485a-a33b-ff8f0a5582e7
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 0c17d28c-63b7-48b4-99f6-837059846e17
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: c2c6ed67-7849-40c7-8388-52bfb9a8cab1
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\samplesuperstore\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

